algoritmo "ex03"
//Contar até que o limite que o usuário determinar, e saltando de 3 em 3
var
   contador, valor, saltar: inteiro
inicio
   contador <- 0
   escreva("Quer contar até quanto: ")
   leia(valor)
   escreva("Qual o será o valr do salto: ")
   leia(saltar)
   enquanto (contador <= valor)faca
      escreval(contador)
      contador <- contador + saltar
   fimEnquanto

   escreval("Fim do loop")

fimalgoritmo